-- 코드를 입력하세요
SELECT
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM
    ANIMAL_INS AS I
    JOIN ANIMAL_OUTS AS E
    ON I.ANIMAL_ID = E.ANIMAL_ID
WHERE
    I.SEX_UPON_INTAKE LIKE 'Intact%' AND
    (E.SEX_UPON_OUTCOME LIKE 'Spayed%' OR E.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID