-- 코드를 입력하세요
SELECT F.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) AS TMP ON F.CATEGORY = TMP.CATEGORY
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유') AND PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC;