-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *, RANK() OVER(
        PARTITION BY CATEGORY
        ORDER BY PRICE DESC
    ) AS PRICE_RANK
    FROM FOOD_PRODUCT
) AS TMP
WHERE PRICE_RANK = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC