SELECT *
FROM
    (SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        ROUND((100 - DISCOUNT_RATE) * DAILY_FEE * 30 / 100) AS FEE
    FROM
        CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE  = P.CAR_TYPE AND DURATION_TYPE LIKE '30%'
    WHERE
        C.CAR_ID NOT IN(
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
        AND C.CAR_TYPE IN ('세단', 'SUV')) AS T
WHERE
    500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC