-- 코드를 입력하세요
SELECT H.CAR_ID, IFNULL(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    LEFT JOIN (
        SELECT CAR_ID, '대여중' AS AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
    ) AS TMP ON H.CAR_ID = TMP.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;