SELECT D.ID, GENOTYPE, PARENT_GENOTYPE
FROM ECOLI_DATA AS D 
    JOIN (SELECT ID, GENOTYPE AS 'PARENT_GENOTYPE' FROM ECOLI_DATA) AS P
        ON D.PARENT_ID = P.ID
WHERE GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY D.ID