-- 코드를 작성해주세요
SELECT 
    E1.ID,
    E1.GENOTYPE,
    (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = E1.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA E1
WHERE E1.GENOTYPE & (
    SELECT E2.GENOTYPE
    FROM ECOLI_DATA E2
    WHERE E2.ID = E1.PARENT_ID
) = (
    SELECT E2.GENOTYPE
    FROM ECOLI_DATA E2
    WHERE E2.ID = E1.PARENT_ID
);