SELECT
    ID,
    GENOTYPE,
    (
        SELECT GENOTYPE
        FROM ECOLI_DATA AS TEMP
        WHERE D.PARENT_ID = TEMP.ID
    ) AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS D
WHERE
    GENOTYPE & (
        SELECT GENOTYPE
        FROM ECOLI_DATA AS TEMP
        WHERE D.PARENT_ID = TEMP.ID
    ) = (
        SELECT GENOTYPE
        FROM ECOLI_DATA AS TEMP
        WHERE D.PARENT_ID = TEMP.ID
    ) 