SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE YEAR(I.JOINED) = 2021 AND YEAR(SALES_DATE) = 2022
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH