WITH RECURSIVE TMP AS (
    SELECT 
        E.ID,
        E.PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA E
    WHERE ISNULL(PARENT_ID)
    
    UNION ALL
    
    SELECT 
        E.ID, E.PARENT_ID, GENERATION + 1 AS GENERATION
    FROM TMP G
    JOIN ECOLI_DATA E
    ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TMP
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION;