-- 코드를 입력하세요
SELECT
    H.CAR_ID, IFNULL(A.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN (
        SELECT
            CAR_ID, '대여중' AS AVAILABILITY
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
) AS A
ON H.CAR_ID = A.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;