WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    
    SELECT HOUR + 1 AS HOUR
    FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A
ON T.HOUR = DATE_FORMAT(A.DATETIME, '%H')
GROUP BY HOUR
ORDER BY HOUR