SELECT
    D1.ID,
    (CASE
        WHEN 0.76 <= COLONY_RATIO THEN 'LOW'
        WHEN 0.51 <= COLONY_RATIO AND COLONY_RATIO <= 0.75 THEN 'MEDIUM'
        WHEN 0.26 <= COLONY_RATIO AND COLONY_RATIO <= 0.50 THEN 'HIGH'
        WHEN COLONY_RATIO <= 0.25 THEN 'CRITICAL'
    END) AS COLONY_NAME
FROM ECOLI_DATA D1
JOIN (
    SELECT D2.ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) / 4 AS COLONY_RATIO
    FROM ECOLI_DATA D2
     ) AS D3
ON D1.ID = D3.ID;