-- 코드를 작성해주세요
SELECT ID, 
    CASE 
        WHEN A = 1 THEN 'CRITICAL'
        WHEN A = 2 THEN 'HIGH'
        WHEN A = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS A
    FROM ECOLI_DATA
) AS TMP
ORDER BY ID