-- 코드를 입력하세요
SELECT
    APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
    JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
    JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD