SELECT
    HISTORY_ID,
    ROUND((100 - IFNULL(
        (
            SELECT 
                MAX(DISCOUNT_RATE)
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE
                CAR_TYPE = '트럭' AND 
                CONVERT(LEFT(DURATION_TYPE, LOCATE('일 이상', DURATION_TYPE) - 1), SIGNED) <= DATEDIFF(END_DATE, START_DATE) + 1
        ), 0
    )) * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;