-- 코드를 작성해주세요
SELECT 
    ID, 
    (SELECT FISH_NAME FROM FISH_NAME_INFO AS N WHERE TMP.FISH_TYPE = N.FISH_TYPE) AS FISH_NAME,
    TMP.LENGTH
FROM FISH_INFO I
JOIN
(
    SELECT MAX(LENGTH) AS LENGTH, I.FISH_TYPE
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE
) AS TMP
ON I.FISH_TYPE = TMP.FISH_TYPE AND I.LENGTH = TMP.LENGTH;