-- 코드를 작성해주세요
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE I.ITEM_ID = PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC