-- 코드를 작성해주세요
SELECT D3.ID
FROM ECOLI_DATA D1
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) AS D2
ON D2.PARENT_ID = D1.ID
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) AS D3
ON D3.PARENT_ID = D2.ID
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) AS D4
ON D4.PARENT_ID = D3.ID
WHERE NOT ISNULL(D3.ID) AND ISNULL(D1.PARENT_ID)
ORDER BY D3.ID;