-- 코드를 입력하세요
SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (
    SELECT
        MAX(PRICE) AS PRICE, CATEGORY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) M ON M.CATEGORY = P.CATEGORY AND M.PRICE = P.PRICE
ORDER BY P.PRICE DESC;